[workspace]
members = [
    "bin/reth",
    "crates/config",
    "crates/consensus/auto-seal",
    "crates/consensus/beacon",
    "crates/consensus/common",
    "crates/blockchain-tree",
    "crates/interfaces",
    "crates/payload/builder",
    "crates/metrics",
    "crates/metrics/metrics-derive",
    "crates/net/common",
    "crates/net/ecies",
    "crates/net/eth-wire",
    "crates/net/discv4",
    "crates/net/dns",
    "crates/net/nat",
    "crates/net/network-api",
    "crates/net/network",
    "crates/net/downloaders",
    "crates/payload/basic",
    "crates/primitives",
    "crates/prune",
    "crates/revm",
    "crates/revm/revm-database",
    "crates/revm/revm-executor",
    "crates/revm/revm-inspectors",
    "crates/revm/revm-parallel",
    "crates/rpc/ipc",
    "crates/rpc/rpc",
    "crates/rpc/rpc-api",
    "crates/rpc/rpc-builder",
    "crates/rpc/rpc-engine-api",
    "crates/rpc/rpc-types",
    "crates/rpc/rpc-testing-util",
    "crates/snapshot",
    "crates/stages",
    "crates/storage/codecs",
    "crates/storage/db",
    "crates/storage/libmdbx-rs",
    "crates/storage/libmdbx-rs/mdbx-sys",
    "crates/storage/provider",
    "crates/storage/nippy-jar",
    "crates/tracing",
    "crates/tasks",
    "crates/transaction-pool",
    "crates/trie",
    "testing/ef-tests",
    "crates/rpc/rpc-types-compat",
    "crates/tokio-util",
    "examples",
    "examples/additional-rpc-namespace-in-cli",
    "examples/cli-extension-event-hooks",
    "examples/rpc-db",
    "examples/manual-p2p",
    "examples/beacon-api-sse",
    "examples/trace-transaction-cli"
]
default-members = ["bin/reth"]

# Explicitly set the resolver to version 2, which is the default for packages with edition >= 2021
# https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html
resolver = "2"

[workspace.package]
version = "0.1.0-alpha.10"
edition = "2021"
rust-version = "1.70" # Remember to update clippy.toml and README.md
license = "MIT OR Apache-2.0"
homepage = "https://paradigmxyz.github.io/reth"
repository = "https://github.com/paradigmxyz/reth"
exclude = [".github/"]

# Like release, but with full debug symbols. Useful for e.g. `perf`.
[profile.debug-fast]
inherits = "release"
debug = true

# Meant for testing - all optimizations, but with debug assertions and overflow
# checks
[profile.hivetests]
inherits = "test"
opt-level = 3

[profile.maxperf]
inherits = "release"
lto = "fat"
codegen-units = 1
incremental = false

[workspace.dependencies]
## reth
reth = { path = "./bin/reth" }
reth-primitives = { path = "./crates/primitives" }
reth-interfaces = { path = "./crates/interfaces" }
reth-provider = { path = "./crates/storage/provider" }
reth-db = { path = "./crates/storage/db" }
reth-rpc-types = { path = "./crates/rpc/rpc-types" }
reth-rpc-builder = { path = "./crates/rpc/rpc-builder" }
reth-blockchain-tree = { path = "./crates/blockchain-tree" }
reth-beacon-consensus = { path = "./crates/consensus/beacon" }
reth-metrics = { path = "./crates/metrics" }
reth-revm = { path = "./crates/revm" }
reth-payload-builder = { path = "./crates/payload/builder" }
reth-transaction-pool = { path = "./crates/transaction-pool" }
reth-tasks = { path = "./crates/tasks" }
reth-network = { path = "./crates/net/network" }
reth-network-api = { path = "./crates/net/network-api" }
reth-rpc-types-compat = { path = "./crates/rpc/rpc-types-compat" }
reth-discv4 = { path = "./crates/net/discv4" }
reth-eth-wire = { path = "./crates/net/eth-wire" }
reth-ecies = { path = "./crates/net/ecies" }
reth-tracing = { path = "./crates/tracing" }
reth-tokio-util = { path = "crates/tokio-util" }
# revm
revm = { git = "https://github.com/bluealloy/revm", rev = "8779d23c0357ba4cb85ab4ef7b26fed98de49706" }
revm-primitives = { git = "https://github.com/bluealloy/revm", rev = "8779d23c0357ba4cb85ab4ef7b26fed98de49706" }

## eth
alloy-primitives = "0.4"
alloy-dyn-abi = "0.4"
alloy-sol-types = "0.4"
alloy-rlp = "0.3"
ethers-core = { version = "2.0", default-features = false }
ethers-providers = { version = "2.0", default-features = false }
ethers-signers = { version = "2.0", default-features = false }
ethers-middleware = { version = "2.0", default-features = false }
discv5 = { git = "https://github.com/sigp/discv5", rev = "f289bbd4c57d499bb1bdb393af3c249600a1c662" }
igd = { git = "https://github.com/stevefan1999-personal/rust-igd", rev = "c2d1f83eb1612a462962453cb0703bc93258b173" }

## js
boa_engine = "0.17"
boa_gc = "0.17"

## misc
aquamarine = "0.3"
bytes = "1.5"
bitflags = "2.4"
clap = "4"
eyre = "0.6"
tracing = "0.1.0"
tracing-appender = "0.2"
thiserror = "1.0"
serde_json = "1.0.94"
serde = { version = "1.0", default-features = false }
rand = "0.8.5"
strum = "0.25"
rayon = "1.7"
itertools = "0.11"
parking_lot = "0.12"
metrics = "0.21.1" # Needed for `metrics-macro` to resolve the crate using `::metrics` notation
hex-literal = "0.4"
once_cell = "1.17"
syn = "2.0"

### proc-macros
proc-macro2 = "1.0"
quote = "1.0"

## tokio
tokio-stream = "0.1.11"
tokio = { version = "1.21", default-features = false }
tokio-util = { version = "0.7.4", features = ["codec"] }

## async
async-trait = "0.1.68"
futures = "0.3.26"
pin-project = "1.0.12"
futures-util = "0.3.25"

## json
jsonrpsee = { version = "0.20" }
jsonrpsee-core = { version = "0.20" }
jsonrpsee-types = { version = "0.20" }

## crypto
secp256k1 = { version = "0.27.0", default-features = false, features = [
    "global-context",
    "rand-std",
    "recovery",
] }
enr = { version = "0.9", default-features = false, features = ["k256"] }
# for eip-4844
c-kzg = "0.1.1"

## config
confy = "0.5"
toml = "0.8"

### misc-testing
arbitrary = "1.1"
assert_matches = "1.5.0"
tempfile = "3.8"

proptest = "1.0"
proptest-derive = "0.4"
serial_test = "2"
