[package]
name = "reth-revm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "reth specific revm utilities"

[dependencies]
# reth
reth-revm-database = { path = "./revm-database" }
reth-revm-inspectors = { path = "./revm-inspectors" }
reth-revm-executor = { path = "./revm-executor" }
reth-revm-parallel = { path = "./revm-parallel", optional = true }

# revm
revm.workspace = true

[features]
parallel = ["reth-revm-parallel"]